# Usa uma imagem oficial do Golang
FROM golang:1.21

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos do projeto
COPY go.mod go.sum ./
RUN go mod download

# Copia o restante dos arquivos
COPY . .

# Define o diretório correto do main.go
WORKDIR /app/cmd

# Compila a aplicação
RUN go build -o main .

# Comando para rodar a aplicação
CMD ["/app/cmd/main"]
