package domain

import (
	"math/rand"
	"time"
)

type Move struct {
	Name     string `json:"name"`
	Type     string `json:"type"`
	Power    int    `json:"pwr"`
	Accuracy string `json:"acuracy"`
	PP       int    `json:"pp"`
	SpaOrNot bool   `json:"spaOrNot"`
	Effect   string `json:"effect"`
}

var Moves = map[string][]Move{
	"Ice":      IceMoves,
	"Fire":     FireMoves,
	"Water":    WaterMoves,
	"Grass":    GrassMoves,
	"Electric": ElectricMoves,
	"Poison":   PoisonMoves,
	"Ground":   GroundMoves,
	"Flying":   FlyingMoves,
	"Psychic":  PsychicMoves,
	"Bug":      BugMoves,
	"Rock":     RockMoves,
	"Ghost":    GhostMoves,
	"Dragon":   DragonMoves,
	"Dark":     DarkMoves,
	"Steel":    SteelMoves,
	"Fairy":    FairyMoves,
	"Fighting": FightingMoves,
	"Normal":   NormalMoves,
}

var IceMoves = []Move{
	{
		Name:     "Ice Beam",
		Type:     "Ice",
		Power:    90,
		Accuracy: "100%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "10% chance to freeze the target.",
	},
	{
		Name:     "Blizzard",
		Type:     "Ice",
		Power:    110,
		Accuracy: "70%",
		PP:       5,
		SpaOrNot: true,
		Effect:   "10% chance to freeze the target.",
	},
	{
		Name:     "Ice Shard",
		Type:     "Ice",
		Power:    40,
		Accuracy: "100%",
		PP:       30,
		SpaOrNot: false,
		Effect:   "Priority +1.",
	},
	{
		Name:     "Icicle Crash",
		Type:     "Ice",
		Power:    85,
		Accuracy: "90%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "30% chance to flinch the target.",
	},
	{
		Name:     "Freeze-Dry",
		Type:     "Ice",
		Power:    70,
		Accuracy: "100%",
		PP:       20,
		SpaOrNot: true,
		Effect:   "10% chance to freeze the target.",
	},
	{
		Name:     "Aurora Veil",
		Type:     "Ice",
		Power:    0,
		Accuracy: "N/A",
		PP:       20,
		SpaOrNot: false,
		Effect:   "For 5 turns, the user and its allies take 50% less damage from physical and special moves.",
	},
	{
		Name:     "Hail",
		Type:     "Ice",
		Power:    0,
		Accuracy: "N/A",
		PP:       10,
		SpaOrNot: false,
		Effect:   "For 5 turns, hail crashes down. It damages all Pokémon except the Ice type.",
	},
	{
		Name:     "Avalanche",
		Type:     "Ice",
		Power:    60,
		Accuracy: "100%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "Power doubles if the user was hit before using this move.",
	},
	{
		Name:     "Frost Breath",
		Type:     "Ice",
		Power:    60,
		Accuracy: "N/A",
		PP:       10,
		SpaOrNot: true,
		Effect:   "Always results in a critical hit.",
	},
	{
		Name:     "Ice Punch",
		Type:     "Ice",
		Power:    75,
		Accuracy: "100%",
	},
}

var FireMoves = []Move{
	{
		Name:     "Flamethrower",
		Type:     "Fire",
		Power:    90,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "10% chance to burn the target.",
	},
	{
		Name:     "Fire Blast",
		Type:     "Fire",
		Power:    110,
		Accuracy: "85%",
		PP:       5,
		SpaOrNot: true,
		Effect:   "10% chance to burn the target.",
	},
	{
		Name:     "Flare Blitz",
		Type:     "Fire",
		Power:    120,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "Recoil 33% of the damage dealt to the target.",
	},
	{
		Name:     "Fire Punch",
		Type:     "Fire",
		Power:    75,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "10% chance to burn the target.",
	},
	{
		Name:     "Heat Wave",
		Type:     "Fire",
		Power:    95,
		Accuracy: "90%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "10% chance to burn the target.",
	},
	{
		Name:     "Sunny Day",
		Type:     "Fire",
		Power:    0,
		Accuracy: "N/A",
		PP:       5,
		SpaOrNot: false,
		Effect:   "For 5 turns, the sun shines brightly. The power of Fire-type moves is increased by 50%.",
	},
	{
		Name:     "Will-O-Wisp",
		Type:     "Fire",
		Power:    0,
		Accuracy: "85%",
		PP:       15,
		SpaOrNot: false,
		Effect:   "Burns the target.",
	},
	{
		Name:     "Fire Spin",
		Type:     "Fire",
		Power:    35,
		Accuracy: "85%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "Traps the target	for 2-5 turns.",
	},
	{
		Name:     "Inferno",
		Type:     "Fire",
		Power:    100,
		Accuracy: "50%",
		PP:       5,
		SpaOrNot: true,
		Effect:   "Burns the target.",
	},
	{
		Name:     "Eruption",
		Type:     "Fire",
		Power:    150,
		Accuracy: "100%",
		PP:       5,
		SpaOrNot: true,
		Effect:   "The lower the user's HP, the less powerful this move becomes.",
	},
}
var WaterMoves = []Move{
	{
		Name:     "Surf",
		Type:     "Water",
		Power:    90,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "No additional effect.",
	},
	{
		Name:     "Hydro Pump",
		Type:     "Water",
		Power:    110,
		Accuracy: "80%",
		PP:       5,
		SpaOrNot: true,
		Effect:   "No additional effect.",
	},
	{
		Name:     "Waterfall",
		Type:     "Water",
		Power:    80,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "20% chance to flinch the target.",
	},
	{
		Name:     "Aqua Jet",
		Type:     "Water",
		Power:    40,
		Accuracy: "100%",
		PP:       20,
		SpaOrNot: true,
		Effect:   "Priority +1.",
	},
	{
		Name:     "Scald",
		Type:     "Water",
		Power:    80,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "30% chance to burn the target.",
	},
	{
		Name:     "Water Pulse",
		Type:     "Water",
		Power:    60,
		Accuracy: "100%",
		PP:       20,
		SpaOrNot: true,
		Effect:   "20% chance to confuse the target.",
	},
	{
		Name:     "Brine",
		Type:     "Water",
		Power:    65,
		Accuracy: "100%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "Power doubles if the target's HP is less than 50%.",
	},
	{
		Name:     "Whirlpool",
		Type:     "Water",
		Power:    35,
		Accuracy: "85%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "Traps the target for 2-5 turns.",
	},
}
var GrassMoves = []Move{
	{
		Name:     "Energy Ball",
		Type:     "Grass",
		Power:    90,
		Accuracy: "100%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "10% chance to lower the target's Special Defense by 1 stage.",
	},
	{
		Name:     "Leaf Storm",
		Type:     "Grass",
		Power:    130,
		Accuracy: "90%",
		PP:       5,
		SpaOrNot: true,
		Effect:   "Lowers the user's Special Attack by 2 stages.",
	},
	{
		Name:     "Leaf Blade",
		Type:     "Grass",
		Power:    90,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "High critical hit ratio.",
	},
	{
		Name:     "Giga Drain",
		Type:     "Grass",
		Power:    75,
		Accuracy: "100%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "User recovers 50% of the damage dealt.",
	},
	{
		Name:     "Solar Beam",
		Type:     "Grass",
		Power:    120,
		Accuracy: "100%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "The user absorbs light in the first turn and attacks in the second turn.",
	},
	{
		Name:     "Synthesis",
		Type:     "Grass",
		Power:    0,
		Accuracy: "N/A",
		PP:       5,
		SpaOrNot: false,
		Effect:   "User recovers HP. The amount of HP regained varies with the weather.",
	},
	{
		Name:     "Leaf Seed",
		Type:     "Grass",
		Power:    40,
		Accuracy: "100%",
		PP:       30,
		SpaOrNot: true,
		Effect:   "User recovers 50% of the damage dealt.",
	},
	{
		Name:     "Grass Knot",
		Type:     "Grass",
		Power:    0,
		Accuracy: "100%",
		PP:       20,
		SpaOrNot: true,
		Effect:   "The heavier the target, the greater the move's power.",
	},
	{
		Name:     "Seed Bomb",
		Type:     "Grass",
		Power:    80,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "No additional effect.",
	},
}
var ElectricMoves = []Move{
	{
		Name:     "Thunderbolt",
		Type:     "Electric",
		Power:    90,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "10% chance to paralyze the target.",
	},
	{
		Name:     "Thunder",
		Type:     "Electric",
		Power:    110,
		Accuracy: "70%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "30% chance to paralyze the target.",
	},
	{
		Name:     "Thunder Punch",
		Type:     "Electric",
		Power:    75,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "10% chance to paralyze the target.",
	},
	{
		Name:     "Thunder Shock",
		Type:     "Electric",
		Power:    40,
		Accuracy: "100%",
		PP:       30,
		SpaOrNot: true,
		Effect:   "10% chance to paralyze	the target.",
	},
	{
		Name:     "Volt Switch",
		Type:     "Electric",
		Power:    70,
		Accuracy: "100%",
		PP:       20,
		SpaOrNot: true,
		Effect:   "User switches out after damaging the target.",
	},
	{
		Name:     "Discharge",
		Type:     "Electric",
		Power:    80,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "30% chance	to paralyze	the target.",
	},
}
var FightingMoves = []Move{
	{
		Name:     "Close Combat",
		Type:     "Fighting",
		Power:    120,
		Accuracy: "100%",
		PP:       5,
		SpaOrNot: true,
		Effect:   "Lowers the user's Defense and Special Defense by 1 stage.",
	},
	{
		Name:     "Dynamic Punch",
		Type:     "Fighting",
		Power:    100,
		Accuracy: "50%",
		PP:       5,
		SpaOrNot: true,
		Effect:   "100% chance to confuse the target.",
	},
	{
		Name:     "Mach Punch",
		Type:     "Fighting",
		Power:    40,
		Accuracy: "100%",
		PP:       30,
		SpaOrNot: true,
		Effect:   "Priority +1.",
	},
	{
		Name:     "Focus Blast",
		Type:     "Fighting",
		Power:    120,
		Accuracy: "70%",
		PP:       5,
		SpaOrNot: true,
		Effect:   "10% chance to lower the target's Special Defense by 1 stage.",
	},
	{
		Name:     "Aura Sphere",
		Type:     "Fighting",
		Power:    80,
		Accuracy: "N/A",
		PP:       20,
		SpaOrNot: true,
		Effect:   "Never misses.",
	},
	{
		Name:     "Superpower",
		Type:     "Fighting",
		Power:    120,
		Accuracy: "100%",
		PP:       5,
		SpaOrNot: true,
		Effect:   "Lowers the user's Attack and Defense by 1 stage.",
	},
	{
		Name:     "Brick Break",
		Type:     "Fighting",
		Power:    75,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "Breaks through Reflect and Light Screen barriers.",
	},
	{
		Name:     "Cross Chop",
		Type:     "Fighting",
		Power:    100,
		Accuracy: "80%",
		PP:       5,
		SpaOrNot: true,
		Effect:   "High critical hit ratio.",
	},
	{
		Name:     "Submission",
		Type:     "Fighting",
		Power:    80,
		Accuracy: "80%",
		PP:       25,
		SpaOrNot: true,
		Effect:   "User receives recoil damage.",
	},
	{
		Name:     "Focus Punch",
		Type:     "Fighting",
		Power:    150,
		Accuracy: "100%",
		PP:       20,
		SpaOrNot: true,
		Effect:   "User cannot move next turn.",
	},
}
var PoisonMoves = []Move{
	{
		Name:     "Sludge Bomb",
		Type:     "Poison",
		Power:    90,
		Accuracy: "100%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "30% chance to poison the target.",
	},
	{
		Name:     "Gunk Shot",
		Type:     "Poison",
		Power:    120,
		Accuracy: "80%",
		PP:       5,
		SpaOrNot: true,
		Effect:   "30% chance to poison the target.",
	},
	{
		Name:     "Sludge Wave",
		Type:     "Poison",
		Power:    95,
		Accuracy: "100%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "10% chance to poison the target.",
	},
	{
		Name:     "Toxic",
		Type:     "Poison",
		Power:    0,
		Accuracy: "90%",
		PP:       10,
		SpaOrNot: false,
		Effect:   "Badly poisons the target.",
	},
	{
		Name:     "Venoshock",
		Type:     "Poison",
		Power:    65,
		Accuracy: "100%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "Power doubles if the target is poisoned.",
	},
	{
		Name:     "Poison Jab",
		Type:     "Poison",
		Power:    80,
		Accuracy: "100%",
		PP:       20,
		SpaOrNot: true,
		Effect:   "30% chance to poison the target.",
	},
	{
		Name:     "Toxic Spikes",
		Type:     "Poison",
		Power:    0,
		Accuracy: "N/A",
		PP:       20,
		SpaOrNot: false,
		Effect:   "Lays a trap of poison spikes at the opponent's feet. The trap hurts opponents that switch into battle.",
	},
	{
		Name:     "Clear Smog",
		Type:     "Poison	",
		Power:    50,
		Accuracy: "N/A",
		PP:       15,
		SpaOrNot: true,
		Effect:   "Eliminates all stat changes.",
	},
	{
		Name:     "Poison Gas",
		Type:     "Poison",
		Power:    0,
		Accuracy: "90%",
		PP:       40,
		SpaOrNot: false,
		Effect:   "Poisons the target.",
	},
	{
		Name:     "Acid",
		Type:     "Poison",
		Power:    40,
		Accuracy: "100%",
		PP:       30,
		SpaOrNot: true,
		Effect:   "10% chance to lower the target's Special Defense by 1 stage.",
	},
	{
		Name:     "Smog",
		Type:     "Poison",
		Power:    30,
		Accuracy: "70%",
		PP:       20,
		SpaOrNot: true,
		Effect:   "40% chance to poison the target.",
	},
}
var GroundMoves = []Move{
	{
		Name:     "Earthquake",
		Type:     "Ground",
		Power:    100,
		Accuracy: "100%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "No additional effect.",
	},
	{
		Name:     "Earth Power",
		Type:     "Ground",
		Power:    90,
		Accuracy: "100%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "10% chance to lower the target's Special Defense by 1 stage.",
	},
	{
		Name:     "Dig",
		Type:     "Ground",
		Power:    80,
		Accuracy: "100%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "Digs underground turn 1, strikes turn 2.",
	},
	{
		Name:     "Bulldoze",
		Type:     "Ground",
		Power:    60,
		Accuracy: "100%",
		PP:       20,
		SpaOrNot: true,
		Effect:   "Lowers the target's Speed by 1 stage.",
	},
	{
		Name:     "Magnitude",
		Type:     "Ground",
		Power:    0,
		Accuracy: "100%",
		PP:       30,
		SpaOrNot: true,
		Effect:   "The power of this move varies.",
	},
	{
		Name:     "Sand Tomb",
		Type:     "Ground",
		Power:    35,
		Accuracy: "85%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "Traps the target for 2-5 turns.",
	},
}

var FlyingMoves = []Move{
	{
		Name:     "Hurricane",
		Type:     "Flying",
		Power:    110,
		Accuracy: "70%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "30% chance to confuse the target.",
	},
	{
		Name:     "Fly",
		Type:     "Flying",
		Power:    90,
		Accuracy: "95%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "Digs underground turn 1, strikes turn 2.",
	},
	{
		Name:     "Aerial Ace",
		Type:     "Flying",
		Power:    60,
		Accuracy: "N/A",
		PP:       20,
		SpaOrNot: true,
		Effect:   "Never misses.",
	},
	{
		Name:     "Roost",
		Type:     "Flying",
		Power:    0,
		Accuracy: "N/A",
		PP:       10,
		SpaOrNot: false,
		Effect:   "User recovers half of its max HP.",
	},
	{
		Name:     "Tailwind",
		Type:     "Flying",
		Power:    0,
		Accuracy: "N/A",
		PP:       15,
		SpaOrNot: false,
		Effect:   "For 4 turns, the Speed of the user's team is doubled.",
	},
	{
		Name:     "Brave Bird",
		Type:     "Flying",
		Power:    120,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "User receives recoil damage.",
	},
	{
		Name:     "Sky Attack",
		Type:     "Flying",
		Power:    140,
		Accuracy: "90%",
		PP:       5,
		SpaOrNot: true,
		Effect:   "Charges turn 1, strikes turn 2.",
	},
	{
		Name:     "Air Slash",
		Type:     "Flying",
		Power:    75,
		Accuracy: "95%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "30% chance to flinch the target.",
	},
	{
		Name:     "Defog",
		Type:     "Flying",
		Power:    0,
		Accuracy: "N/A",
		PP:       15,
		SpaOrNot: false,
		Effect:   "Lowers the target's evasion by 1 stage.",
	},
}
var PsychicMoves = []Move{
	{
		Name:     "Psychic",
		Type:     "Psychic",
		Power:    90,
		Accuracy: "100%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "10% chance to lower the target's Special Defense by 1 stage.",
	},
	{
		Name:     "Psyshock",
		Type:     "Psychic",
		Power:    80,
		Accuracy: "100%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "Deals physical damage.",
	},
	{
		Name:     "Psybeam",
		Type:     "Psychic",
		Power:    65,
		Accuracy: "100%",
		PP:       20,
		SpaOrNot: true,
		Effect:   "10% chance to confuse the target.",
	},
	{
		Name:     "Future Sight",
		Type:     "Psychic",
		Power:    120,
		Accuracy: "100%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "Deals damage in 2 turns.",
	},
	{
		Name:     "Psywave",
		Type:     "Psychic",
		Power:    0,
		Accuracy: "80%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "The power of this move varies.",
	},
	{
		Name:     "Confusion",
		Type:     "Psychic",
		Power:    50,
		Accuracy: "100%",
		PP:       25,
		SpaOrNot: true,
		Effect:   "10% chance to confuse the target.",
	},
	{
		Name:     "Telekinesis",
		Type:     "Psychic",
		Power:    0,
		Accuracy: "N/A",
		PP:       15,
		SpaOrNot: false,
		Effect:   "For 3 turns, the target is immune to Ground-type moves.",
	},
	{
		Name:     "Extrasensory",
		Type:     "Psychic",
		Power:    80,
		Accuracy: "100%",
		PP:       20,
		SpaOrNot: true,
		Effect:   "10% chance to flinch the target.",
	},
	{
		Name:     "Heal Pulse",
		Type:     "Psychic",
		Power:    0,
		Accuracy: "N/A",
		PP:       10,
		SpaOrNot: false,
		Effect:   "Restores 50% of the target's max HP.",
	},
	{
		Name:     "Psycho Cut",
		Type:     "Psychic",
		Power:    70,
		Accuracy: "100%",
		PP:       20,
		SpaOrNot: true,
		Effect:   "High critical hit ratio.",
	},
}
var BugMoves = []Move{
	{
		Name:     "U-Turn",
		Type:     "Bug",
		Power:    70,
		Accuracy: "100%",
		PP:       20,
		SpaOrNot: true,
		Effect:   "User switches out after damaging the target.",
	},
	{
		Name:     "Megahorn",
		Type:     "Bug",
		Power:    120,
		Accuracy: "85%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "No additional effect.",
	},
	{
		Name:     "Bug Buzz",
		Type:     "Bug",
		Power:    90,
		Accuracy: "100%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "10% chance to lower the target's Special Defense by 1 stage.",
	},
	{
		Name:     "X-Scissor",
		Type:     "Bug",
		Power:    80,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "No additional effect.",
	},
	{
		Name:     "Signal Beam",
		Type:     "Bug",
		Power:    75,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "10% chance to confuse the target.",
	},
	{
		Name:     "Bug Bite",
		Type:     "Bug",
		Power:    60,
		Accuracy: "100%",
		PP:       20,
		SpaOrNot: true,
		Effect:   "If the target is holding a Berry, the user eats it and the effect depends on the Berry.",
	},
	{
		Name:     "Struggle Bug",
		Type:     "Bug",
		Power:    50,
		Accuracy: "100%",
		PP:       20,
		SpaOrNot: true,
		Effect:   "Lowers the target's Special Attack by 1 stage.",
	},
	{
		Name:     "Bug Bite",
		Type:     "Bug",
		Power:    60,
		Accuracy: "100%",
		PP:       20,
		SpaOrNot: true,
		Effect:   "If the target is holding a Berry, the user eats it and the effect depends on the Berry.",
	},
	{
		Name:     "Infestation",
		Type:     "Bug",
		Power:    20,
		Accuracy: "100%",
		PP:       20,
		SpaOrNot: true,
		Effect:   "Traps the target	for 4-5 turns.",
	},
}
var RockMoves = []Move{
	{
		Name:     "Stone Edge",
		Type:     "Rock",
		Power:    100,
		Accuracy: "80%",
		PP:       5,
		SpaOrNot: true,
		Effect:   "High critical hit ratio.",
	},
	{
		Name:     "Rock Slide",
		Type:     "Rock",
		Power:    75,
		Accuracy: "90%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "30% chance to flinch the target.",
	},
	{
		Name:     "Rock Blast",
		Type:     "Rock",
		Power:    25,
		Accuracy: "90%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "Hits 2-5 times in one turn.",
	},
	{
		Name:     "Rock Tomb",
		Type:     "Rock",
		Power:    60,
		Accuracy: "95%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "Lowers the target's Speed by 1 stage.",
	},
	{
		Name:     "Stealth Rock",
		Type:     "Rock",
		Power:    0,
		Accuracy: "N/A",
		PP:       20,
		SpaOrNot: false,
		Effect:   "Lays a trap of levitating stones around the opponent's team. The trap hurts opponents that switch into battle.",
	},
	{
		Name:     "Rock Polish",
		Type:     "Rock",
		Power:    0,
		Accuracy: "N/A",
		PP:       20,
		SpaOrNot: false,
		Effect:   "Sharply raises the user's Speed.",
	},
	{
		Name:     "Smack Down",
		Type:     "Rock",
		Power:    50,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "Makes Flying-type Pokémon vulnerable to Ground moves.",
	},
	{
		Name:     "Head Smash",
		Type:     "Rock",
		Power:    150,
		Accuracy: "80%",
		PP:       5,
		SpaOrNot: true,
		Effect:   "User receives recoil damage.",
	},
}

var GhostMoves = []Move{
	{
		Name:     "Shadow Ball",
		Type:     "Ghost",
		Power:    80,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "20% chance to lower the target's Special Defense by 1 stage.",
	},
	{
		Name:     "Shadow Claw",
		Type:     "Ghost",
		Power:    70,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "High critical hit ratio.",
	},
	{
		Name:     "Shadow Punch",
		Type:     "Ghost",
		Power:    60,
		Accuracy: "N/A",
		PP:       20,
		SpaOrNot: true,
		Effect:   "Never misses.",
	},
	{
		Name:     "Hex",
		Type:     "Ghost",
		Power:    65,
		Accuracy: "100%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "Power doubles if the target has a status condition.",
	},
	{
		Name:     "Night Shade",
		Type:     "Ghost",
		Power:    0,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "Deals damage equal to the user's level.",
	},
	{
		Name:     "Curse",
		Type:     "Ghost",
		Power:    0,
		Accuracy: "N/A",
		PP:       10,
		SpaOrNot: false,
		Effect:   "Ghosts pay half their max HP to hurt the target every turn.",
	},
	{
		Name:     "Nightmare",
		Type:     "Ghost",
		Power:    0,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: false,
		Effect:   "A sleeping target is hurt by 25% of its max HP every turn.",
	},
	{
		Name:     "Ominous Wind",
		Type:     "Ghost",
		Power:    60,
		Accuracy: "100%",
		PP:       5,
		SpaOrNot: true,
		Effect:   "10% chance to raise all of the user's stats by 1 stage.",
	},
	{
		Name:     "Lick",
		Type:     "Ghost",
		Power:    30,
		Accuracy: "100%",
		PP:       30,
		SpaOrNot: true,
		Effect:   "30% chance to paralyze the target.",
	},
	{
		Name:     "Confuse Ray",
		Type:     "Ghost",
		Power:    0,
		Accuracy: "100%",
		PP:       10,
		SpaOrNot: false,
		Effect:   "Confuses the target.",
	},
}
var DragonMoves = []Move{
	{
		Name:     "Dragon Pulse",
		Type:     "Dragon",
		Power:    85,
		Accuracy: "100%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "No additional effect.",
	},
	{
		Name:     "Draco Meteor",
		Type:     "Dragon",
		Power:    130,
		Accuracy: "90%",
		PP:       5,
		SpaOrNot: true,
		Effect:   "Lowers the user's Special Attack by 2 stages.",
	},
	{
		Name:     "Outrage",
		Type:     "Dragon",
		Power:    120,
		Accuracy: "100%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "User attacks for 2-3 turns but then becomes confused.",
	},
	{
		Name:     "Dragon Claw",
		Type:     "Dragon",
		Power:    80,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "No additional effect.",
	},
	{
		Name:     "Dragon Rush",
		Type:     "Dragon",
		Power:    100,
		Accuracy: "75%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "20% chance to flinch the target.",
	},
	{
		Name:     "Dragon Tail",
		Type:     "Dragon",
		Power:    60,
		Accuracy: "90%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "Forces the target to switch to a random ally.",
	},
	{
		Name:     "Dragon Dance",
		Type:     "Dragon",
		Power:    0,
		Accuracy: "N/A",
		PP:       20,
		SpaOrNot: false,
		Effect:   "Raises the user's Attack and Speed by 1 stage.",
	},
	{
		Name:     "Roar of Time",
		Type:     "Dragon",
		Power:    150,
		Accuracy: "90%",
		PP:       5,
		SpaOrNot: true,
		Effect:   "User must recharge next turn.",
	},
}
var DarkMoves = []Move{
	{
		Name:     "Dark Pulse",
		Type:     "Dark",
		Power:    80,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "20% chance to flinch the target.",
	},
	{
		Name:     "Night Slash",
		Type:     "Dark",
		Power:    70,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "High critical hit ratio.",
	},
	{
		Name:     "Pursuit",
		Type:     "Dark",
		Power:    40,
		Accuracy: "100%",
		PP:       20,
		SpaOrNot: true,
		Effect:   "Deals double damage if the target is switching out.",
	},
	{
		Name:     "Crunch",
		Type:     "Dark",
		Power:    80,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "20% chance to lower the target's Defense by 1 stage.",
	},
	{
		Name:     "Foul Play",
		Type:     "Dark",
		Power:    95,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "Uses the target's Attack stat.",
	},
	{
		Name:     "Night Shade",
		Type:     "Dark",
		Power:    0,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "Deals damage equal to the user's level.",
	},
	{
		Name:     "Embargo",
		Type:     "Dark",
		Power:    0,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: false,
		Effect:   "The target is unable to use items.",
	},
	{
		Name:     "Taunt",
		Type:     "Dark",
		Power:    0,
		Accuracy: "100%",
		PP:       20,
		SpaOrNot: false,
		Effect:   "For 3 turns, the target can't use status moves.",
	},
	{
		Name:     "Torment",
		Type:     "Dark",
		Power:    0,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: false,
		Effect:   "The target is unable to use the same move twice in a row.",
	},
	{
		Name:     "Sucker Punch",
		Type:     "Dark",
		Power:    70,
		Accuracy: "100%",
		PP:       5,
		SpaOrNot: true,
		Effect:   "Priority +1.",
	},
}
var SteelMoves = []Move{
	{
		Name:     "Iron Head",
		Type:     "Steel",
		Power:    80,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "30% chance to flinch the target.",
	},
	{
		Name:     "Iron Tail",
		Type:     "Steel",
		Power:    100,
		Accuracy: "75%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "30% chance to lower the target's Defense by 1 stage.",
	},
	{
		Name:     "Metal Claw",
		Type:     "Steel",
		Power:    50,
		Accuracy: "95%",
		PP:       35,
		SpaOrNot: true,
		Effect:   "10% chance to raise the user's Attack by 1 stage.",
	},
	{
		Name:     "Bullet Punch",
		Type:     "Steel",
		Power:    40,
		Accuracy: "100%",
		PP:       30,
		SpaOrNot: true,
		Effect:   "Priority +1.",
	},
	{
		Name:     "Flash Cannon",
		Type:     "Steel",
		Power:    80,
		Accuracy: "100%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "10% chance to lower the target's Special Defense by 1 stage.",
	},
	{
		Name:     "Steel Wing",
		Type:     "Steel",
		Power:    70,
		Accuracy: "90%",
		PP:       25,
		SpaOrNot: true,
		Effect:   "10% chance to raise the user's Defense by 1 stage.",
	},
	{
		Name:     "Meteor Mash",
		Type:     "Steel",
		Power:    90,
		Accuracy: "90%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "20% chance to raise the user's Attack by 1 stage.",
	},
	{
		Name:     "Gyro Ball",
		Type:     "		Steel",
		Power:    0,
		Accuracy: "100%",
		PP:       5,
		SpaOrNot: true,
		Effect:   "The slower the user, the greater the damage.",
	},
}
var FairyMoves = []Move{
	{
		Name:     "Moonblast",
		Type:     "Fairy",
		Power:    95,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "30% chance to lower the target's Special Attack by 1 stage.",
	},
	{
		Name:     "Dazzling Gleam",
		Type:     "Fairy",
		Power:    80,
		Accuracy: "100%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "No additional effect.",
	},
	{
		Name:     "Play Rough",
		Type:     "Fairy",
		Power:    90,
		Accuracy: "90%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "10% chance to lower the target's Attack by 1 stage.",
	},
	{
		Name:     "Moonlight",
		Type:     "Fairy",
		Power:    0,
		Accuracy: "N/A",
		PP:       5,
		SpaOrNot: false,
		Effect:   "User recovers HP. The amount of HP regained varies with the weather.",
	},
	{
		Name:     "Fairy Wind",
		Type:     "Fairy",
		Power:    40,
		Accuracy: "100%",
		PP:       30,
		SpaOrNot: true,
		Effect:   "No additional effect.",
	},
	{
		Name:     "Draining Kiss",
		Type:     "Fairy",
		Power:    50,
		Accuracy: "100%",
		PP:       10,
		SpaOrNot: true,
		Effect:   "User recovers 75% of the damage dealt.",
	},
	{
		Name:     "Mist Ball",
		Type:     "Fairy",
		Power:    70,
		Accuracy: "100%",
		PP:       5,
		SpaOrNot: true,
		Effect:   "50% chance to lower the target's Special Attack by 1 stage.",
	},
	{
		Name:     "Fairy Lock",
		Type:     "Fairy",
		Power:    0,
		Accuracy: "N/A",
		PP:       10,
		SpaOrNot: false,
		Effect:   "Prevents all Pokémon from fleeing or switching out during the next turn.",
	},
}

var NormalMoves = []Move{
	{
		Name:     "Hyper Beam",
		Type:     "Normal",
		Power:    150,
		Accuracy: "90%",
		PP:       5,
		SpaOrNot: true,
		Effect:   "User cannot move next turn.",
	},
	{
		Name:     "Giga Impact",
		Type:     "Normal",
		Power:    150,
		Accuracy: "90%",
		PP:       5,
		SpaOrNot: true,
		Effect:   "User cannot move next turn.",
	},
	{
		Name:     "Double-Edge",
		Type:     "Normal",
		Power:    120,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "User receives recoil damage.",
	},
	{
		Name:     "Body Slam",
		Type:     "Normal",
		Power:    85,
		Accuracy: "100%",
		PP:       15,
		SpaOrNot: true,
		Effect:   "30% chance	to paralyze	the target.",
	},
}

func RandomMoveTypeKey() string {
	src := rand.NewSource(time.Now().UnixNano())
	r := rand.New(src)
	keys := make([]string, 0, len(Moves))
	for k := range Moves {
		keys = append(keys, k)
	}
	return keys[r.Intn(len(keys))]
}

func RandomMove(moveList []Move) Move {
	src := rand.NewSource(time.Now().UnixNano())
	r := rand.New(src)
	randint := r.Intn(len(moveList))
	return moveList[randint]
}

func GetRandonMoveList() []Move {

	randomKey := RandomMoveTypeKey()
	randonMoveList := Moves[randomKey]
	return randonMoveList
}
