package domain

type Ability struct {
	Name   string `json:"name"`
	Effect string `json:"effect"`
}

var Abilities = []Ability{
	{Name: "Overgrow", Effect: "Powers up Grass-type moves when the Pokémon's HP is low."},
	{Name: "Blaze", Effect: "Powers up Fire-type moves when the Pokémon's HP is low."},
	{Name: "Torrent", Effect: "Powers up Water-type moves when the Pokémon's HP is low."},
	{Name: "Swarm", Effect: "Powers up Bug-type moves when the Pokémon's HP is low."},
	{Name: "Shield Dust", Effect: "Blocks the added effects of attacks taken."},
	{Name: "Static", Effect: "Contact with the Pokémon may cause paralysis."},
	{Name: "Keen Eye", Effect: "Prevents other Pokémon from lowering its accuracy."},
	{Name: "Run Away", Effect: "Enables a sure getaway from wild Pokémon."},
	{Name: "Guts", Effect: "Boosts Attack if there is a status problem."},
	{Name: "Sand Veil", Effect: "Boosts the Pokémon's evasion in a sandstorm."},
	{Name: "Rivalry", Effect: "Becomes competitive and deals more damage to Pokémon of the same"},
	{Name: "Intimidate", Effect: "Lowers the opposing Pokémon's Attack stat."},
	{Name: "Unnerve", Effect: "Makes the opposing Pokémon nervous and unable to eat Berries."},
	{Name: "Sand Rush", Effect: "Boosts the Pokémon's Speed stat in a sandstorm."},
	{Name: "Sand Force", Effect: "Boosts certain moves' power in a sandstorm."},
	{Name: "Iron Fist", Effect: "Boosts the power of punching moves."},
	{Name: "Reckless", Effect: "Powers up moves that have recoil damage."},
	{Name: "Sheer Force", Effect: "Removes additional effects to increase the power of moves."},
	{Name: "Magic Guard", Effect: "The Pokémon only takes damage from attacks."},
	{Name: "No Guard", Effect: "Ensures attacks by or against the Pokémon land."},
	{Name: "Sturdy", Effect: "It cannot be knocked out with one hit."},
	{Name: "Magnet Pull", Effect: "Prevents Steel-type Pokémon from escaping."},
	{Name: "Static", Effect: "Contact with the Pokémon may cause paralysis."},
	{Name: "Flame Body", Effect: "Contact with the Pokémon may burn the attacker."},
	{Name: "Vital Spirit", Effect: "Prevents the Pokémon from falling asleep."},
	{Name: "Anger Point", Effect: "Maxes Attack after taking a critical hit."},
	{Name: "Defiant", Effect: "Boosts Attack when its stats are lowered."},
	{Name: "Justified", Effect: "Boosts Attack when hit by a Dark-type move."},
	{Name: "Rattled", Effect: "Boosts Speed when hit by a Bug-, Ghost-, or Dark-type move."},
	{Name: "Magic Bounce", Effect: "Reflects status moves, instead of getting hit by them."},
	{Name: "Synchronize", Effect: "Passes on a burn, poison, or paralysis to the foe."},
	{Name: "Inner Focus", Effect: "The Pokémon is protected from flinching."},
	{Name: "Steadfast", Effect: "Boosts Speed each time the Pokémon flinches."},
	{Name: "Oblivious", Effect: "Prevents the Pokémon from becoming infatuated."},
	{Name: "Own Tempo", Effect: "Prevents the Pokémon from becoming confused."},
	{Name: "Cloud Nine", Effect: "Eliminates the effects of weather."},
	{Name: "Compound Eyes", Effect: "Boosts the accuracy of moves."},
	{Name: "Tinted Lens", Effect: "Powers up “not very effective” moves."},
	{Name: "Frisk", Effect: "The Pokémon can check the foe's held item."},
	{Name: "Infiltrator", Effect: "Passes through the foe's barrier and strikes."},
	{Name: "Limber", Effect: "The Pokémon is protected from paralysis."},
	{Name: "Sand Veil", Effect: "Boosts the Pokémon's evasion in a sandstorm."},
	{Name: "Water Absorb", Effect: "Restores HP if hit by a Water-type move."},
	{Name: "Volt Absorb", Effect: "Restores HP if hit by an Electric-type move."},
	{Name: "Flash Fire", Effect: "Powers up the Pokémon's Fire-type moves if it's hit by one."},
	{Name: "Flame Body", Effect: "Contact with the Pokémon may burn the attacker."},
	{Name: "Water Veil", Effect: "Prevents the Pokémon from getting a burn."},
	{Name: "Pressure", Effect: "The Pokémon raises the foe's PP usage."},
	{Name: "Super Luck", Effect: "Heightens the critical-hit ratios of moves."},
	{Name: "Quick Feet", Effect: "Boosts Speed if there is a status problem."},
	{Name: "Natural Cure", Effect: "All status problems are healed upon switching out."},
	{Name: "Serene Grace", Effect: "Boosts the likelihood of added effects appearing."},
	{Name: "Poison Point", Effect: "Contact with the Pokémon may poison the attacker."},
	{Name: "Poison Touch", Effect: "May poison a target when the Pokémon makes contact."},
	{Name: "Poison Heal", Effect: "Restores HP if the Pokémon is poisoned."},
	{Name: "Immunity", Effect: "Prevents the Pokémon from getting poisoned."},
	{Name: "Toxic Boost", Effect: "Powers up physical attacks when the Pokémon is poisoned."},
	{Name: "Flare Boost", Effect: "Powers up special attacks when the Pokémon is burned."},
	{Name: "Gluttony", Effect: "Encourages the early use of a held Berry."},
	{Name: "Sticky Hold", Effect: "Protects the Pokémon from item theft."},
	{Name: "Storm Drain", Effect: "Draws in all Water-type moves to up Sp. Attack."},
	{Name: "Sap Sipper", Effect: "Boosts Attack when hit by a Grass-type move."},
	{Name: "Hyper Cutter", Effect: "Prevents the Attack stat from being lowered."},
	{Name: "Big Pecks", Effect: "Protects the Pokémon from Defense-lowering attacks."},
	{Name: "Mold Breaker", Effect: "Moves can be used regardless of Abilities."},
	{Name: "Unaware", Effect: "Ignores any change in Ability by the foe."},
	{Name: "Tangled Feet", Effect: "Raises evasion if the Pokémon is confused."},
	{Name: "Frisk", Effect: "The Pokémon can check the foe's held item."},
	{Name: "Pickup", Effect: "The Pokémon may pick up items."},
	{Name: "Technician", Effect: "Powers up the Pokémon's weaker moves."},
	{Name: "Skill Link", Effect: "Increases the frequency of multi-strike moves."},
	{Name: "Analytic", Effect: "Boosts move power when the Pokémon moves last."},
	{Name: "Sniper", Effect: "Powers up moves if they become critical hits."},
	{Name: "Aftermath", Effect: "Damages the attacker landing the finishing hit."},
	{Name: "Frisk", Effect: "The Pokémon can check the foe's held item."},
	{Name: "Keen Eye", Effect: "Prevents other Pokémon from lowering its accuracy."},
	{Name: "Pickpocket", Effect: "Steals an item when hit by another Pokémon."},
	{Name: "Prankster", Effect: "Gives priority to a status move."},
	{Name: "Defiant", Effect: "Boosts Attack when its stats are lowered."},
	{Name: "Defeatist", Effect: "Halves stats when HP becomes half or less."},
	{Name: "Moxie", Effect: "Boosts Attack after knocking out any Pokémon."},
}
